apiVersion: v1
kind: Secret
metadata:
  name: maas-usage-logging-bucket
  namespace: redhat-ods-monitoring
stringData:
  access_key_id: ${S3_ACCESS_KEY_ID}
  access_key_secret: ${S3_SECRET_ACCESS_KEY}
  bucketnames: maas-usage-logging
  endpoint: https://s3.openshift-storage.svc:443