apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: maas-usage-logging-claim
  namespace: redhat-ods-monitoring
spec:
  bucketName: maas-usage-logging
  storageClassName: openshift-storage.noobaa.io