---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: open-cluster-management
    server: https://kubernetes.default.svc
  project: default
  source:
    path: acm/operator
    repoURL: https://github.com/joshgav/openshift-services.git
    targetRevision: main
    kustomize: {}
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-operand
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: open-cluster-management
    server: https://kubernetes.default.svc
  project: default
  source:
    path: acm/base
    repoURL: https://github.com/joshgav/openshift-services.git
    targetRevision: main
    kustomize: {}
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-gitops
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: open-cluster-management
    server: https://kubernetes.default.svc
  project: default
  source:
    path: acm/argocd
    repoURL: https://github.com/joshgav/openshift-services.git
    targetRevision: main
    kustomize: {}
  syncPolicy:
    automated: {}
    retry:
      limit: -1
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
