---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: istio-system-ambient
    openshift.io/cluster-monitoring: "true"
    istio-discovery: ambient
  name: istio-system-ambient
