apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: velero-default-dpa
  namespace: openshift-adp
spec:
  backupImages: false
  backupLocations:
    - velero:
        config:
          # insecureSkipTLSVerify: 'true'
          profile: default
          region: noobaa
          s3ForcePathStyle: 'true'
          s3Url: 'https://s3-openshift-storage.apps.${OPENSHIFT_CLUSTER_NAME}.${OPENSHIFT_BASE_DOMAIN}'
        credential:
          key: credentials
          name: bsl-credentials
        default: true
        objectStorage:
          bucket: oadp-backup
        provider: aws
  configuration:
    nodeAgent:
      enable: true
      uploaderType: kopia
    velero:
      defaultSnapshotMoveData: true
      defaultPlugins:
        - openshift
        - aws
        - kubevirt
        - csi
      featureFlags:
        - EnableCSI