kind: Secret
apiVersion: v1
metadata:
  name: maas-db-config
  namespace: redhat-ods-applications
stringData:
  # retrieve from secret maas-app, key uri
  DB_CONNECTION_URL: postgresql://username:password@maas-rw.redhat-ods-applications:5432/app
type: Opaque
