apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default-dsc
spec:
  components:
    aipipelines:
      argoWorkflowsControllers:
        managementState: Managed 
      managementState: Managed
    dashboard:
      managementState: Managed
    feastoperator:
      managementState: Removed
    aigateway:
      managementState: Managed
      modelsAsAService:
        managementState: Managed
    kserve:
      managementState: Managed
    kueue:
      managementState: Removed
    modelregistry:
      managementState: Managed
    ray:
      managementState: Removed
    trainingoperator:
      managementState: Removed
    trustyai:
      managementState: Managed
    workbenches:
      managementState: Managed
    mlflowoperator:
      managementState: Managed
    ogx:
      managementState: Managed