apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: redhat-gpt-oss-20b
  namespace: llm
  labels:
    opendatahub.io/dashboard: 'true'
    networking.kserve.io/visibility: exposed
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: redhat-gpt-oss-20b
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/hardware-profile-name: gpu
    opendatahub.io/model-type: generative
    serving.kserve.io/deploymentMode: RawDeployment
    security.opendatahub.io/enable-auth: "true"
spec:
  predictor:
    timeout: 300
    automountServiceAccountToken: false
    deploymentStrategy:
      type: Recreate
    maxReplicas: 1
    minReplicas: 1
    model:
      args: []
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '2'
          memory: 4Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '2'
          memory: 4Gi
          nvidia.com/gpu: '1'
      runtime: redhat-gpt-oss-20b
      storageUri: 'oci://quay.io/redhat-ai-services/modelcar-catalog:gpt-oss-20b'
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists