apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: llama-32-deployment
  namespace: my-model
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: llama-3.2-deployment
    serving.kserve.io/deploymentMode: RawDeployment
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/hardware-profile-name: gpu
    opendatahub.io/connections: llama-32-3b-instruct
    opendatahub.io/model-type: generative
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: RollingUpdate
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - '--max-model-len=110000'
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '2'
          memory: 16Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '2'
          memory: 8Gi
          nvidia.com/gpu: '1'
      runtime: llama-32-deployment
      storageUri: 'oci://quay.io/redhat-ai-services/modelcar-catalog:llama-3.2-3b-instruct'
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists